### ISSUE TITLE
Matrix Math

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#13]
I don't know much about licensing...Can we just pull in the functions from the  [PEAR Math Matrix Library](https://pear.php.net/package/Math_Matrix)  as a starting point? Regression functions will be much better with the addition of Matrix functions. Simple Linear Regression is just a simplification of Multiple Linear Regression. Polynomial fit will be arbitrarily easy.
I've used this library before, and my only issue with it as-is is it modifies $this when performing operations like invert() and mult() instead of returning a new object. This means you can't chain operations like $X->Transpose()->mult($X);

**Comment by markrogoyski** [comment]
I'm not familiar with the PHP license and what restrictions it has. For now please do not use any potentially restrictive licensed code.
I was planning on creating a LinearAlgebra namespace that would have vector and matrix operations. I can get started on that after merging and updating the recent changes if that works for you.

**Comment by Beakerboy** [comment]
No worries, I wasn't planning on merging anything that I hadn't written. There are a few Matrix Libraries in composer that might work as starting points too.

**Comment by markrogoyski** [comment]
I added an initial Math\LinearAlgebra namespace with Vector and Matrix classes. I still have some methods to add but it should be enough to get started working with. Let me know if you have any particular features you want added. Usage is documented in the main page README.

**Comment by Beakerboy** [comment]
It definitely needs inverse and determinant before I can use it to expand the regressions.

**Comment by markrogoyski** [comment]
Those are on my list of functions to implement.

**Comment by Beakerboy** [comment]
Besides concatenation, another good matrix function would be "exclusion". 

    $M = new Matrix([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]];
    print $m->rowExclude(2); 
    // [[1,2,3,4,5],
    //  [3,4,5,6,7]]
    print $M->columnExclude(3);
 //      [[1,2,4,5],
   //     [2,3,5,6],
   //     [3,4,6,7]]

Calculating the standard errors of multiple linear regression is simplified by using this.

**Comment by Beakerboy** [comment]
I've been reading up on the MIT license, and it looks like we could just grab any matrix code from another MIT licensed project, and use it, as long as the original author's copyright is included. Since I've contributed a fair amount of code, I should probably get credit too. Would you object to pulling some matrix code into our project and modifying the project license?

**Comment by markrogoyski** [comment]
I've slowly been working on adding the matrix operations by working it out. I added LU Decomposition, which will be a step in adding solving linear equations and doing inverse and determinant etc. It's been a long time since I've studied linear algebra so I've been relearning as I go.
I'd prefer that all code be original, and if you don't mind waiting, I'll try to get it done. Or, if you want to take a stab at it, that's cool too. I don't think there is anything preventing you from looking at someone else's code to learn the general logic of how something works (This is general math after all), and then write your own implementation.
Otherwise, if you want to start with the other person's code and modify it from there, we will have to include the license. Since this project is already MIT and I already have an MIT license in the root directory I don't think we need a second license file, since it isn't like we are incorporating GPL code or something, so I think we can give the original source credit in the method's Docbloc comments and that should suffice. If you know of some projects that do the same thing that we can verify on how to do it that would be helpful. Another option is to have the other author contribute here and do a pull request.

Btw, back when you first started contributing I added your name to the authors section of the composer file. For example, when you look at the project on any page that parses the composer manifest, such as Packagist, you will see it appear:
https://packagist.org/packages/markrogoyski/math-php

**Comment by markrogoyski** [comment]
Looking around on the Web, it looks like how some people do it is if you copy the code verbatim, you want to site the source and provide the license text. This could be done at the top of the class that includes the included code or in the docblock of the method if it is just one method.

If you are going to reference it as a base of understanding to adapt the code or implement it on your own, it seems OK to site the source of the original code and give credit that it was used as a reference without needing to include the license, since the original licensed code was not used

I'm not an expert in this, but that seems reasonable to me.

**Comment by markrogoyski** [comment]
I added an initial implementation of Matrix inverse, determinant and reduced echelon form. See if these work for you.
