### ISSUE TITLE
Polynomial Class

### ISSUE THREAD

**Issue by jakobsandberg** [markrogoyski/math-php#143]
These are problems that have been found, and that I am currently working on:
- The constant polynomial p(x) = 1 prints an empty string, whereas it should print 1
- Differentiation of a constant polynomial does not yield 0

**Comment by jakobsandberg** [comment]
It looks like differentiation a constant polynomial returns a polynomial with an empty coefficient array: `new Polynomial([]);`

Thus, when you try to print it, it completely skips the `foreach ($this->coefficients as $i => $coefficient)` loop.

To solve this, I have added a small statement after the loop: `$polynomial = ($polynomial !== '') ? $polynomial : '0';` This makes the polynomial string '0' if it is empty after the `foreach` loop, and return it normally otherwise.

**Comment by jakobsandberg** [comment]
For the first problem, it looks like the constant polynomial p(x) = 1 is getting caught by the following in __toString:

```
// Drop coefficients that equal 1 (and -1)
if ($coefficient == 1) {
    $coefficient = '';
}
```

And it is the only coefficient, thus an empty string is being returned.

I have updated it slightly to also require that the current degree is nonzero:

```
// Drop coefficients that equal 1 (and -1) if they are not the 0th-degree term
if ($coefficient == 1 and $this->degree - $i != 0) {
    $coefficient = '';
}
```

This should also fix `__toString()` for ALL polynomials with a zero-th degree coefficient of 1.

**Comment by jakobsandberg** [comment]
In terms of differentiating a constant, I have included this to fix the evaluation as well:

```
$derivativeCoefficients = ($derivativeCoefficients !== []) ? $derivativeCoefficients : [0];
```

**Comment by markrogoyski** [comment]
Thanks for reviewing everything and making fixes. Going forward, let's try to make sure there are unit tests for all the different edge cases.

If you are familiar with TDD (Test-driven development), it is a style of development where you write the unit tests first, covering a thorough set of standard use cases and every edge case you can think of, and then you get feedback as you develop to know if your function is doing what it is supposed to.  For something like math, where you generally are going to know ahead of time what your inputs and expected outputs are, TDD can be really beneficial as you are coding things. If your initial test suite is thorough enough, you know that your function works as soon as all the tests pass. Then, you can refactor and improve things with confidence because the unit tests continue to check that the function continues to do what you expect it to do.

A common workflow would be:
 1) Define function inputs and output
 2) Write thorough set of unit tests
 3) Develop initial version of function that is correct and works (Checked by unit tests)
 4) Refactor and improve upon design until satisfied (regressions prevented by unit tests)

You get the benefit of unit tests checking correctness, and providing protection against regressions all during the initial development.

Just thought I'd introduce the idea of TDD in case that methodology interests you.

Thanks again for all your contributions.

**Comment by jakobsandberg** [comment]
Mark,

Thanks for the advice and thorough explanation! I am definitely going to try out this methodology as it sounds very practical and effective, especially for a project like this.

**Comment by markrogoyski** [comment]
OK to close this issue?

**Comment by jakobsandberg** [comment]
Yes! I can close it now
