### ISSUE TITLE
Distribution naming and namespaces

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#15]
It looks like there are both continuous and discrete uniform interval distributions....which looks like a problem than be solved my either class naming standards, or namespacing. Would you prefer a Math\Probability\Distribution\Continuous and Discrete namespaces, or just keep everything in Distribution? 

On a similar vein, do you think all the classes and files need to have 'Distribution' in their names? Would things be cleaner to just have 'StandardNormal.php'?

**Comment by markrogoyski** [comment]
Two separate namespaces:
Math\Probability\Distribution\Continuous
Math\Probability\Distribution\Discrete

And since they are under a Distribution namespace, there is no need to put Distribution in any of the class names.

Then each can also have a unique base class to inherit from, since Continuous would have a PDF method, and a Discrete would have a pmf method, etc.

**Comment by Beakerboy** [comment]
Done in the Distribution pull request.

**Comment by Beakerboy** [comment]
The Discrete classes have been moved as well.  There's a pull request for it.
