### ISSUE TITLE
how can I do t-test?

### ISSUE THREAD

**Issue by giupardeb** [markrogoyski/math-php#171]
Exists a function to calculate t-test?

**Comment by markrogoyski** [comment]
Hi,

There are functions for one-sample and two-samples t-tests.

```php
use MathPHP\Statistics\Significance;

// T test - One sample (t and p values)
$Hₐ = 280; //Alternate hypothesis (M Sample mean)
$s  = 50;  // SD of sample
$n  = 15;  // Sample size
$H₀ = 300; // Null hypothesis (μ₀ Population mean)
$t  = Significance::tTestOneSample($Hₐ, $s, $n, $H);
/* [
  't'  => -1.549, // t score
  'p1' => 0.0718, // one-tailed p value
  'p2' => 0.1437, // two-tailed p value
] */

// T test - Two samples (t and p values)
$μ₁ = 42.14; // Sample mean of population 1
$μ₂ = 43.23; // Sample mean of population 2
$n₁ = 10;    // Sample size of population 1
$n₂ = 10;    // Sample size of population 2
$σ₁ = 0.683; // Standard deviation of sample mean 1
$σ₂ = 0.750; // Standard deviation of sample mean 2
$t  = Significance::tTestTwoSample($μ₁, $μ₂, $n₁, $n₂, $σ₁, $σ₂);
/* [
  't'  => -3.3978,  // t score
  'p1' => 0.001604, // one-tailed p value
  'p2' => 0.181947, // two-tailed p value
] */
```

Does this answer your question?

**Comment by Beakerboy** [comment]
Would it make sense to extend this function to where it accepts two arrays of data instead of all the statistics on the data? This function can then calculate the averages, counts, and standard deviations. In excel, t-tests can be performed three ways, you can pool the data to calculate one standard deviation, estimate two standard deviations, or pair the data and test the difference of the pairs.

**Comment by markrogoyski** [comment]
Yeah, I considered that option as well. I think R does it that way. Most of the online t-test calculators used the individual statistics as input. Both ways are valid and useful.

I think it could be useful to have an alternate version, or overload the current function to accept the array(s) of data as an option. I would not replace the current function with it though, because often when you are doing a test for significance, you already have worked with the data and know these stats. There is also the scenario where you don't have access to the raw data and these stats are all that is available to you, which is a common scenario.

Rather than have two versions of the function, I think it makes sense to overload the current function to accept either kind of input. This will require more input checking/validation in the implementation, but will make usage more convenient for multiple input scenarios.

Thanks for the feedback.

**Comment by markrogoyski** [comment]
Opened a separate issue for enhancing the t-test to take in raw data input.

**Comment by giupardeb** [comment]
@markrogoyski YES! I could not find it..thank you so much!
