### ISSUE TITLE
Matrix-Vector-multiplication with Vector result

### ISSUE THREAD

**Issue by aboks** [markrogoyski/math-php#173]
Currently `Matrix::multiply` accepts either a `Matrix` or a `Vector`, but the result is always a `Matrix`. If one wants to do matrix-vector-multiplication and obtain a `Vector`, this requires something like
```
$resultVector = new Vector($matrix->multiply($vector)->getColumn(0));
```

It would be nice if there was a convenience function for such multiplication, something along the lines of
```
$resultVector = $matrix->vectorMultiply($vector);
```
I'd be happy to contribute a PR for this, but first wanted to check if you would consider this a good idea.

**Comment by markrogoyski** [comment]
Hi,

Thanks for your interest in Math PHP!

I get what you are saying. Since an m x n matrix times a n vector is always going to be a vector, why not have a special vector multiplication method on a matrix that will return a vector.

I think I am OK with this. The reason matrix multiply returns a matrix is because it is matrix multiplication, and it really should only accept matrices as input, but to be flexible it accepts vectors and treats them as a 1 x n matrix.

I implemented vectorMultiply in the develop branch. Please take a look and see if this works for you. And let me know if you have any other feedback, improvements, suggestions, etc.

Thanks.

**Comment by aboks** [comment]
Yes, that's great! Thank you for creating such an awesome PHP math library.

One further thought (although it would probably be more of a long-term idea): since a vector is just a 1 x n matrix, shouldn't `Vector` share an interface with/extend from `Matrix`, and thus have all methods that a `Matrix` has? Some operations (like `inverse`) may sound strange on a `Vector`, but then again they should technically make sense on a square (1 x 1) vector. Might be an idea to think about.

**Comment by markrogoyski** [comment]
That's an interesting idea for Vector so share an operational interface with Matrix. I'll create a new issue for that to consider what the implications are and allow other people to provide feedback.

Thanks.

**Comment by markrogoyski** [comment]
This feature (vectorMultiply) is in the latest release, version 0.16.0.
