### ISSUE TITLE
Can this work with php version 5.6 

### ISSUE THREAD

**Issue by tinasherobert** [markrogoyski/math-php#185]
Im failing to host the library on godday with php version 5.6 please help

**Comment by markrogoyski** [comment]
Hi,

Thank you for your interest in Math PHP!

I'm sorry you had issues getting it to work on your GoDaddy host. Unfortunately Math PHP requires PHP 7 or greater. There are two reasons for this.

**1) Scalar type declarations (Formerly called type hints)**
Being able to declare types in method declarations and have them enforced eliminates hundreds of lines of boilerplate precondition code and possibly thousands of lines of unit tests to check those type preconditions. This reduces code complexity and results in a higher percentage of function code that is related to the relevant mathematical function, rather than PHP language noise.

**2) PHP 5.6 is no longer actively supported.**
http://php.net/supported-versions.php

Unfortunately, Math PHP will not work on PHP 5.6 and there is no plan to do so. Sorry about that.
