### ISSUE TITLE
Divide by Zero Error

### ISSUE THREAD

**Issue by Ascerta** [markrogoyski/math-php#259]
A number of functions in RandomVariable can result in a divide by zero exception being thrown, e.g SEK if n is 3 or -5. Should the affected functions indicate that they can thrown an error or handle it themselves?

I've most often seen this as a problem when running the stats describe function over an array of values. The exception causes the whole function to fail rather than the individual property.

**Comment by Beakerboy** [comment]
My vote is to modify the method so it checks $n and throws an Exception if it is below the minimum number of samples necessary for the function. I’m not familiar with the SEK function, so cannot speak for what the minimum $n is.

**Comment by Ascerta** [comment]
The 'skewness' functions also throw a divide by zero error if all the values are same. Would it be correct to calculate the standard deviation first in the skewness functions and return 0 if SD is 0?

**Comment by markrogoyski** [comment]
Thanks for the feedback. I'll review the descriptive statistics and random variable functions and add better error handling. Also, when you have an issue, if you can provide specific unit tests that reproduce the issue that is helpful. Thanks.

**Comment by markrogoyski** [comment]
For Standard Error of Skewness (SES) n has to be greater than 2.
For Standard Error of Kurtosis (SEK) n has to be greater than 3.

I think for these methods, they should be modified to throw a proper exception if the data set is not large enough. And that is fine.

The issue is what to do with describe, as that has no requirement on size of the data set. I think the best option is to just provide a null value for SES and SEK in those cases where those functions are not applicable to the data set.

**Comment by markrogoyski** [comment]
This issue, along with in general better exception and error case handling, has been included in the latest release, v0.38.0.

Thank you for bringing this issue to our attention, and thank you for your continued interest in MathPHP.
