### ISSUE TITLE
matrix isSquareAndSymmetric()

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#305]
I noticed this method is not listed in the docblock. Is there a reason to have a function that is called "ThisAndThat" with the code `return this() && that();` Also, does "square AND symmetric" make any sense? Isn't any symmetric matrix also square by definition? In fact, I could see making the isSymmetric code a little more optimized by short-circuiting the need to transpose and saying:

````php
    public function isSymmetric(): bool
    {
        return $this->isSquare() && $this->transpose()->isEqual($this);
    }
````
so if the matrix is not square, we know it's not symmetric and the the expression will automatiicaly evaluate without running the transpose and equality check. (~~at least I'm pretty sure PHP short-circuits boolean expressions~~ it does).

**Comment by markrogoyski** [comment]
From the definition of symmetric matrix:
> Because equal matrices have equal dimensions, only square matrices can be symmetric.

There is code I wrote a year ago, six months ago, that I look at today, and ask, "Why did I do it like that?" Often times it is because I'm always learning and becoming a better programmer, and would no longer do it that way. In this case, I was probably thinking a descriptive method was easier to grok than a multi-conditional statement, but it also breaks the single responsibility principle. And I clearly didn't think about the definition of symmetric matrix.

Refactoring is just part of programming. Unit tests allow refactoring. The ```isSymmetric``` method should start off with an ```isSquare``` check, and then we only need to check if a matrix is symmetric for those cases.

Thanks for picking up on this. (This is why code reviews are important)

**Comment by markrogoyski** [comment]
The improvements have been implemented in the develop branch.
