### ISSUE TITLE
Constructor for Big Integer

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#321]
I'm making an arbitrary length integer class. The object is initialized with a string in a particular base:
````php
$obj = new BigInt('123456789012345678901234567890')
// or
$obj1 =  new BigInt('f54a5851e9372b87810a8e60cdd2e7cfd80b6e31', 16)
````

each number base has a particular 'alphabet' associated with it, '01' for binary '0123456789' for decimal, etc. There are many number base encodings out there, so I want to make the constructor flexible. I had initially thought
````php
function __construct(string $number, int $base = 10, string $alphabet = null)
{
    if ($alphabet === null) {
        $alphabet = self::defaultAlphabet($base);
    } else {
        if (strlen($alphabet !== $base)) {
            throw \Exception;
        }
    }
........
````

But, given an alphabet string, we can calculate the base, so maybe this is better:
````php
/**
 * @param mixed $base
 *   int or string, where if a string is given, the base is strlen($base)
 */
function __construct(string $number, $base = 10)
{
    if (is_string($base)) {
        $alphabet = $base;
        $base = strlen($base);
    } else {
        $alphabet = self::defaultAlphabet($base);
    }
.......
````

My idea is to have class constants of the alphabets of the common bases, and, given an integer base, use the default alphabet for that number, unless overridden by the user.

I currently have a working class and have tested that it can correctly calculate the factorial of 1000. As a reminder, the idea is to provide long number support, since you did not want the end user to have to enable the GMP module.

**Comment by markrogoyski** [comment]
Hi. Thanks for the update.

Another option to consider for construction: since PHP does not have method/constructor overloading, you could create static factory methods for each base or whatever to simply the interface. Basically, keep the constructor flexible, but simplify the user's interface to it.

For example:
```php
public function __construct(string $number, $base = 10)
{
    // ...
}

public static function createFromNumber(string $number): BigInt
{
    return new BigInt($number, 10);
}

public static function createFromHex(string $string): BigInt
{
    return new BigInt($number, 16);
}

// ...
```

Sometimes people will go as far as to make the constructor private to force the factory methods to be used.

**Comment by Beakerboy** [comment]
Good point. Let me know if you have a preference and I’ll run with it.

**Comment by markrogoyski** [comment]
If there are only a few cases, like number, hex, and binary, then I think static factory methods on the BigInt class itself is a good place to put them. Construction is not so complicated. However, if there are going to be like 13 ways to construct a BigInt (like the Matrix class), then moving the responsibility of construction into its own factory class makes sense, because construction in itself is complex.

As a general programming principle, the logic for construction is not needed once the object comes into existence, so if construction is a complex process, then moving that out of the class and into its own area of responsibility allows the constructed class to be a lot simpler. There is the tradeoff of having to work with yet another class to do the construction. I usually recommend keeping everything in one class until it is clear that there are multiple responsibilities and then refactor the separate responsibilities out into separate classes. In Agile, you plan to get it wrong the first couple times and allow room to improve the design as you go forward.

**Comment by Beakerboy** [comment]
The new number object has been merged
