### ISSUE TITLE
Grubbs test, possible undefined $G

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#324]
PHPStan at level 7 suggests that $G on line 78 of Grubbs could be undefined. $G is never initialized, and it is always set within `if` statements. Something should probably also happen when the type is not one of the defined constants. For example, all the places where $G is set could instead return, and if it reaches the bottom, throw an exception.

**Comment by markrogoyski** [comment]
PHPStan is a good tool. I use it myself when developing. You might also notice a lot of small pull requests in the past where I made small changes because of suggestions from the tool. FYI, there is a Make target to run PHPStan on the entire codebase.

In this case, returning early in each if block is probably the preferable solution. There is no need to throw a LogicException at the end, because it would be dead code that could not be reached. Someone could modify the ```validateGrubbsTestType``` function, but short of that, that exception would not be reachable. The OOP solution to this would be to have the ```$typeOftest``` parameter be a type that represented the only valid test types. However, this would put a larger effort on the user of the library to call this function, so it is not worth it.

**Comment by markrogoyski** [comment]
I updated the method to return as soon as G is computed.
Commit: https://github.com/markrogoyski/math-php/commit/81ffedbd5c10532c125699a017a7ccecc3e7709d


_Output from PHPStan_
```
~/php/vagrant/php/math-php $ vendor/bin/phpstan analyze --level max src/Statistics/Outlier.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


 [OK] No errors

```
