### ISSUE TITLE
Statistics - Descriptive

### ISSUE THREAD

**Issue by docdik** [markrogoyski/math-php#366]
Hello.
Just to let you know, I've been using many of your stats and matrix packages.    I have noticed an issue with Kurtosis and Skewness in Statistics - Descriptive.    with a different php resource I get different values and these agree with SPSS and online javascript based calculators.  When I plug your test array into my test site using Math PHP,  the output is the same as your test data output, suggesting an error in your functions.   Look at time block 1 in the screenshot.   the top kurtosis and skewness figures are from math PHP the lower are from Al Kashi php.
<img width="525" alt="Screenshot 2020-01-27 at 12 00 26" src="https://user-images.githubusercontent.com/8442770/73173316-026fb400-40fd-11ea-8be0-d5d748295d40.png">

**Comment by Beakerboy** [comment]
I confirmed that Excel produces 1.47 and .774.

Excel help states it uses:

    n(n+1)/(n-1)/(n-2)/(n-3) Σ((x-μ)/s)⁴ - 3(n-1) ²/(n-2)/(n-3)

**Comment by markrogoyski** [comment]
Hi @docdik 

Thank you for your interest in MathPHP and improving it.

Skewness and Kurtosis are interesting. Think of them more like a concepts rather than a formulas. When people look at a plot of a distribution, they usually agree by how it looks whether it is skewed or not. However, how to determine this mathematically with a formula is where a lot of people differ.

Skewness has a few different formulas. There is no "correct" formula. MathPHP provides three common skewness formulas and leaves it up to the user to decide which one to use.

```php
// Given
$data = [13, 18, 13, 14, 13, 16, 14, 21, 13];

// Let's call this the classic textbook definition: 1.1600970628842
$skewnews = RandomVariable::skewness($data);

// Population skewness: 1.23046875
// R calls this skewness(type=1), Excel calls this SKEW.P
$populationSkewness = RandomVariable::populationSkewness($data);

// Sample skewness: 1.4915533665654
// R calls this skewness(type=2), Excel calls this SKEW
$sampleSkewness = RandomVariable::sampleSkewness($data);
```

Based on the calculations you are matching against, it looks like you want to use `sampleSkewness` for your skewness calculation.

For reference: https://en.wikipedia.org/wiki/Skewness
R code
```R
> skewness(data, type=1)
[1] 1.230469
> skewness(data, type=2)
[1] 1.491553
```

Kurtosis is very similar to skewness in that there are multiple definitions in how to calculate it. MathPHP at this time only provides one measurement of kurtosis. The MathPHP formula matches the R `kurtosis(type=1)` which R defines as _This is the typical definition used in many older textbooks._

MathPHP
```php
// 0.1728515625
$kurtosis = RandomVariable::kurtosis($data);
```

R
```R
> kurtosis(data, type=1)
[1] 0.1728516
```

If you think it would be useful, we could add additional calculations for kurtosis if you think it is important to get different measurements for it.

Does this make sense? I think better documentation would help users understand what each calculation is doing. Also, it might be worth a discussion about what the default `skewness` function should calculate.

Thoughts?
Thanks,
Mark

**Comment by docdik** [comment]
Hi Mark
Thanks for getting back and a very full explanation.   As you can certainly
tell I am no expert, I'm a physicist with reasonable maths, some
programming skills and a slowly growing knowledge of stats,   writing stats
software for psychology!!!   What I am doing is getting the Psychology Prof
I am working with to conduct experiments and output the results in SPSS and
using this as a basis for my output direct from mysql.
I am also checking results with online packages and JASP and R,  JASP is
excellent, give it a go if you have not spotted it yet
https://jasp-stats.org/   it is free.   As another check I have just stuck
your test data into JASP and the output gives sample skewness and no other
option that I can see and a different value for kurtosis.    see screen
grab.
I honestly do not know the most appropriate thing for MathPHP, but I would
have thought the default in statistics-descriptive bit should probably be
what all the main packages provide.
All the best
Richard

**Comment by markrogoyski** [comment]
Hi @docdik,

Sorry for the confusion in the function interface. I think this is good feedback. I will consider changing the default `skewness` method to provide a "more common formula" like Excel or SPSS/R. And to make the interface more common like other functions in the library (like SD, variance, etc.), i think I will add optional parameters to `skewness` to change the formula it uses.

Thanks for the feedback. I will make these changes in the next release.

Mark

**Comment by docdik** [comment]
Hi Mark
sounds good and thanks.  I should add that Mathphp is exceptional it has
assisted my work greatly :)
Cheers
Richard

**Comment by markrogoyski** [comment]
Hi @docdik,

The latest version, [v0.58.0](https://github.com/markrogoyski/math-php/releases/tag/v0.58.0), has improvements for skewness. The default skewness function will now return the result that is similar to what Excel's SKEW and SAS/SPSS return. There is also now an optional type parameter for skewness to change the algorithm similar to how R does it. The individual functions are still available.

Thanks again for the feedback. I will do a similar improvement for kurtosis in the next release.

**Comment by docdik** [comment]
Excellent, thanks Mark!

**Comment by markrogoyski** [comment]
Hi @docdik,

The latest version, [v0.59.0](https://github.com/markrogoyski/math-php/releases/tag/v0.59.0), has improvements to kurtosis. The default kurtosis function now return the result that is similar to what Excel's KURT and SAS/SPSS return. Similar to skewness, kurtosis now also has an optional type parameter to change the algorithm similar to how R does it. Individual functions for population and sample kurtosis were also added.

Thanks again for the feedback. The library's default behavior has improved because of your suggestions.
