### ISSUE TITLE
Replace calls to self with static

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#375]
I imagine we will eventually have users that will be extending some of our classes for their own projects. There are several places where a class will return a version of itself with something like:

````
class Foo
{
  public function bar()
  {
      // do stuff
      return new Foo();
   }
}
````

Would it make sense to replace that last call to `new static()`. This way, it it is extended, the function will not have to be rewritten by the user.

**Comment by markrogoyski** [comment]
Replacing `new Class()` with late static binding doesn't change functionality unless the class is extended, so it seems fine. You have the option to declare a class final if you want to prohibit someone from extending it.

The Matrix is the class that comes to mind that is an object that returns itself all over the place. But most of its internal return matrices are created using the MatrixFactory, so this wouldn't be helpful there. I don't recall any distributions or regressions returning themselves. Is there a place where we could use this now?

Anyways, if it does come up, sure. Go ahead and return a late static binding instead of itself.

**Comment by Beakerboy** [comment]
The ArbitraryInteger class returns itself.

**Comment by markrogoyski** [comment]
Ahh. I missed that one. ArbitraryInteger does return itself. Sure. Let's change it to late static binding.

**Comment by markrogoyski** [comment]
I've changed the ArbitraryInteger instantiation with late static binding. Thanks for the suggestion. Going forward let's just use late static binding for any classes that return themselves. I don't see any reason not to always do this.
