### ISSUE TITLE
Prepare for PHP8.

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#406]
PHP8 will be released soon. Do you think it’s worth testing against the prerelease to ensure the library will run from day 1?

**Comment by markrogoyski** [comment]
Yeah. I added 8.0 to the matrix of versions for the Github CI actions. I'll add it to Travis as well when I have a minute (unless you want to add it now and see if it works).

**Comment by Beakerboy** [comment]
No need. I thought I’d throw it out since I knew you were working on GitHub Actions.

**Comment by markrogoyski** [comment]
Some PHPUnit tests do not run on PHP 8. PHPUnit has a class called "Match" which is now a keyword in PHP 8. The fix is in PHPUnit 9.3, but that only supports PHP 7.3 and greater. I have to check if PHPUnit back ported it to PHPUnit 8, which supports 7.2.

One option is to remove or rewrite those unit tests, as they are testing private methods.

**Comment by markrogoyski** [comment]
Version 2.0 supports PHP 8.0.
