### ISSUE TITLE
SetOperationsTest failures with PHPUnit 9.5

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#418]
It seems that PHPUnit8.5 does not support Code Coverage reporting for PHP8. I experimented with PHPUnit9.5 and it installs, but the SetOperationsTest file has 42 failures. I wonder if data type matters for this assertion in 9.5.

```
MathPHP\Tests\SetTheory\SetOperationsTest::testIntersect with data set #10 (array(1, 2, 3, 'a', 'b', MathPHP\SetTheory\Set Object (...)), array(1, 'a', 'k'), array(1, 'a'), MathPHP\SetTheory\Set Object (...))
Failed asserting that an array contains '1'.
```

**Comment by markrogoyski** [comment]
In the develop and master PR Github Actions I set code coverage to run on PHP 7.4 and I think it works. It looks like the pull request Github Actions config is set to PHP 8.0 and I probably never tested it. Let's set it to 7.4 for now.

Unfortunately PHPUnit 9 doesn't support PHP 7.2, so that's why the library uses 8 for now.
https://phpunit.de/supported-versions.html

**Comment by markrogoyski** [comment]
I updated the unit tests in the develop branch. They will pass with PHP 9.5. There were quite a few issues. There will be some warnings about deprecated functions, but it will not fail the test run. Thanks for letting me know about the issue.
