### ISSUE TITLE
Testing distribution::rand()

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#49]
I don't know unit testing enough to mock it up correctly. I was thinking the test directory could have something like this, but it looks fishy the way it is. Any advice?

    class TestDistribution extends Continuous
    {
        public static function rand($x)
        {
            // Have the parent call the method below which returns a float that is specified by the test.
            // If you assume that the PHP random number generator works, we will test if the method works
            // given a specific value.  Then again, if we have already tested the inverse function, in this case we
            // pretty much know it works.
            return parent::rand();
        }

        static function randomFloat()
        {
            return self::x;
        }
    }

**Comment by markrogoyski** [comment]
You can't mock static functions in PHPUnit; only object methods.

If static method a uses static method b, you'd want to have unit tests on method b on its own. Then the tests on static method a are testing just a, since you know your tests on b test that that works properly.

Now, if method b is a random number generator, then it is going to be impossible to test specific output since the output will depend on the rng. The best you could do is test that it is a number, that it is within the range of possible values based on the range of the rng, etc.

This doesn't necessarily sound like an issue of not being able to mock static methods, but that a rng is being used. Even if there was just one static method and it used a PHP rand function, your output is dependent on that, and you can't know exactly what the output will be.

**Comment by markrogoyski** [comment]
Thinking about this a little more, a possibly elegant solution is to make your static method a higher-order function that accepts as an additional parameter a function (PHP callable closure) that will act as the random number generator. Then for unit tests, you can pass in your testRNG function that returns non-random numbers so you can test the expected output of your method knowing what the inputs will be because you seeded the RNG with your own values.

Then, from a user interface perspective, you might want to wrap that higher-order function with a convenience wrapper method that will supply the standard RNG, but still give the user the option to directly call it with their own RNG if they want.

Just an idea.

**Comment by Beakerboy** [comment]
I think I have a better solution. If I add the Dirac Delta as a distribution, I could add it's inverse function to the DiracDetla class, which would override the parent inverse function. The inverse of the Dirac Delta is Zero for all values of p.

**Comment by Beakerboy** [comment]
This is in a pull request.
