### ISSUE TITLE
Standard normal inheritance

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#51]
I see you have the standard normal inheriting from Continuous instead of Normal. I'm curious why you changed that?

**Comment by markrogoyski** [comment]
The function signatures are different.
StandardNormal: PDF($z)
Normal: PDF($x, $μ, $σ)

PHP will fatal error if you try to extend a class and change the function signature.

**Comment by Beakerboy** [comment]
ahh. Is that new in PHP7? I don't remember earlier version doing that.

**Comment by markrogoyski** [comment]
Maybe a really old version of PHP might have only issued a strict standards warning or something, but since 5 onward I think it has been a fatal error.

In general, you want to follow this:
https://en.wikipedia.org/wiki/Liskov_substitution_principle

Basically, any parent/child class could be used in the same manner without the code that uses it knowing the difference. It should take the same kind of input and return the same kind of output.

**Comment by Beakerboy** [comment]
Thanks for the reference material. As a jack of many trades, there's always things to improve upon.
