### ISSUE TITLE
Parameter range in functions

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#57]
Should we move the error-checking function so it can be used by other functions throughout the library?

**Comment by markrogoyski** [comment]
I thought about that. It makes sense in the distributions because all the methods are related and use the same parameters. But a lot of the other classes are collections of functions that don't necessarily share the parameters. So, each method would also have to define the limits parameter when it calls the checkLimits method. Not a big deal, but not as convenient as just passing a common limits constant. I think maybe in \Math\Functions having a class for internal helper functions might be a good idea. That's already where Map lives.

**Comment by markrogoyski** [comment]
Moved to Math\Functions\Support.
