### ISSUE TITLE
SquareMatrix Questions

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#91]
If I do:

    $S = new SquareMatrix([[1,2],[3,4]]);
    $N = $S->scalarAdd(5);
    echo get_class($N);

Would it be a Matrix, or SquareMatrix? The parent scalarAdd() is set to return a Matrix. If we want to maintain a matrix as a square matrix, would all the parent functions have to be redefined in the child?

The reason I'm asking, is we need to make sure that 

        $S = new SquareMatrix([[1,2],[3,4]]);
        $N = $S->columnExclude(1);
        echo get_class($N);

does not return an object of type SquareMatrix. I'm worried that type hinting could cause issues. If I do a series of operations, I wouldn't want to have to manually "upconvert" my Matrix to a SquareMatrix in order to do a specific function.

    $X->transpose()->multiply($X)->toSquare()->inverse();

It's like in the stereotypical "Car" class, having to make a special LittleRedCorvette class in order to play Prince on the radio.

**Comment by markrogoyski** [comment]
Right now I was only returning a Square Matrix where it was guaranteed to be so (identity, cofactor). And the only difference is that Square Matrix knows it isSquare, where as a regular Matrix has to check if it isSquare. You should never need to convert a Matrix to be square because a Matrix can check if it isSquare before it performs an operation. The Square Matrix just has the slight optimization that the isSquare check is instant.

In your example, the end result after the columnExclude would be a 1x2 Matrix, so it wouldn't be square. But regular operations don't need to return anything other than a regular Matrix, because anything that works on a SquareMatrix, will work on a regular Matrix that isSquare.

I wouldn't type hint anything with SquareMatrix because a regular Matrix could also be Square. A possible refactor could be for every matrix operation to check what type of matrix it is creating and return the appropriate type, and then type hinting could be used to eliminate isSquare checks and stuff, but for now I was just adding it just to add it.

**Comment by markrogoyski** [comment]
Taking it further, I was thinking about creating a MatrixFactory class that would be how you instantiate Matrices, and that would take care of returning the appropriate type of Matrix.

**Comment by markrogoyski** [comment]
If the Matrix operation functions were going to type hint for the specific Matrix type, then there would need to be more variations of Matrix class. Because if something type hints for only a SquareMatrix, and you want to pass in a FunctionMatrix or VandermondeMatrix or whatever, then you would also need FunctionSquareMatrix and VandermondeSquareMatrix types that extend SquareMatrix. For now just having each type of Matrix self report isSquare seems the simplest solution. Although, there is a nice elegance to type hinting in that it allows you to remove all the boilerplate ` if (!isSquare()) { throw \Exception }` code.

**Comment by Beakerboy** [comment]
Seeing the Factory in action will probably clear everything up for me. I think I get it.

**Comment by markrogoyski** [comment]
I added the MatrixFactory and refactored a bunch of stuff to use the Factory. I also added Square variants of some of the matrices.
Take a look at the MatrixFactory class and it should be pretty clear how it works. The `MatrixFactory::create` is how you would create a matrix regardless of what type it is. It will figure out the appropriate matrix based on the input parameters.

The one downside I came across is that since PHP is a single-inheritance language, something like a VandermondeSquareMatrix can't both have a parent of SquareMatrix and VandermondeMatrix, so you have to pick one. I figured there would be more potential for type hinting and saving cycles of testing isSquare() with a parent of SquareMatrix than inheriting from Vandermonde, so I went with that (I didn't put that much thought into it though). If you need to specifically check that something is a Vandermonde, you'd have to then do an `if instanceof ` kind of check for both kinds of Vandermonde Matrices.

Let me know if anything doesn't make sense. The main design goal is for the user/methods to just have one way to create a Matrix and it will give them the most appropriate/specific Matrix based on the parameters.

**Comment by Beakerboy** [comment]
The single inheritance isn't a problem. A Vandermonde is unlikely to be square...and if it is, it's not by design. A Vadermonde is typically a design matrix for a regression, and will be transposed and multiplied by itself. Only then will it be Square.

**Comment by Beakerboy** [comment]
I like the new Matrix axiom tests. That's a great idea!

**Comment by markrogoyski** [comment]
Thanks. I was thinking what would be a kind of 'functional test' or 'integration test' for this library. After you have full test coverage of individual methods, it is nice to have larger functional tests that make use of multiple methods and classes working together to test something meaningful that shows it all works.
