### ISSUE TITLE
Symmetric matrix class?

### ISSUE THREAD

**Issue by Beakerboy** [markrogoyski/math-php#97]
Would a separate symmetric matrix class make sense? Only half the matrix data would need to be saved to memory. It would be pretty easy to change the matrix multiplication code to account for the absence of half the values. A special function in the Matrix factory(or somewhere) could take a matrix times it's inverse and return a symmetric matrix.

**Comment by markrogoyski** [comment]
I read about something like that in my Matrix Computations book. It seems to be a large tradeoff in increasing time (CPU operations) and code complexity to save memory. The user or whatever Matrix operation that provided the data to the constructor would have had all the Matrix data in the first place, so it would already have been in memory at one point I would think. This seems to defeat the purpose of saving space since it already has been allocated at that point.

If it can be done in a way that makes an improvement in one area (space/memory) without a large increase in another area (time or code complexity) then it would make sense. I'm just not a fan of premature optimizations that come at a cost of code complexity and understanding of what the code is doing. As long as it was clear and well documented then it would be fine.

**Comment by Beakerboy** [comment]
Got it. I just thought I'd throw it out there. I started going through the MIT Opencourseware on Linear Algebra, since I never took it in college. The Professor had a section of them. Also, looking at Wikipedia on the subject and saw this:

> Symmetric matrices appear naturally in a variety of applications, and typical numerical linear algebra software makes special accommodations for them.

**Comment by markrogoyski** [comment]
It certainly makes sense as an optimization. I'm just not familiar enough with that optimization to know how to handle it in a way where it actually improves performance rather than just create more overhead to deal with the 'optimization.'
